development:
  adapter: postgresql
  database: tsentin_development
  username: despo
  password:
  min_messages: WARNING
  host: localhost
  encoding: utf8

test: &test
  adapter: postgresql
  database: tsentin_test
  username: despo
  password:
  min_messages: WARNING
  host: localhost
  encoding: utf8

production:
  adapter: postgresql
  database: tsentin_production
  username: despo
  password:
  min_messages: WARNING
  host: localhost
  encoding: utf8
